name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2022buildtools --no-progress --confirm
        choco install visualstudio-installer --no-progress --confirm
        cmd /C "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --quiet --wait --installPath "C:\BuildTools" --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.Component.MSBuild

    - name: Restore Dependencies
      run: msbuild AtlasToolbox-WinUI3.sln /t:restore

    - name: Build Solution
      run: msbuild AtlasToolbox-WinUI3.sln /p:Configuration=Release

    - name: Publish Artifacts
      run: dotnet publish AtlasToolbox-WinUI3.sln --configuration Release --output ./artifacts

    - name: Create ZIP of EXE
      run: powershell Compress-Archive -Path ./artifacts/* -DestinationPath ./AtlasToolbox.zip

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AtlasToolbox
        path: ./AtlasToolbox.zip
