name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore Dependencies
      run: msbuild AtlasToolbox-WinUI3.sln /t:restore

    - name: Build Solution
      run: msbuild AtlasToolbox-WinUI3.sln /p:Configuration=Release /p:Platform="x64"

    - name: Publish Artifacts
      run: dotnet publish AtlasToolbox/AtlasToolbox.csproj --configuration Release

    - name: List Published Files (for Debugging)
      run: dir "AtlasToolbox/bin/x64/Release/net8.0-windows10.0.26100.0/publish"

    - name: Create ZIP of EXE
      run: powershell Compress-Archive -Path "AtlasToolbox/bin/x64/Release/net8.0-windows10.0.26100.0/publish/*" -DestinationPath ./AtlasToolbox.zip

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AtlasToolbox
        path: ./AtlasToolbox.zip
